export enum NodeType {
  STORY = "STORY",
  SECTION = "SECTION",
  SUBSECTION = "SUBSECTION",
  JUMP = "JUMP",
  PARAGRAPH = "PARAGRAPH",
  TEXT_CONTENT = "TEXT_CONTENT",
  EXPRESSION = "EXPRESSION",
  BRANCH = "BRANCH",
  OPTION = "OPTION",
  INPUT = "INPUT",
  EMPTY = "EMPTY",
  END = "END"
}
